#Config Server
server:
  port: 8080
  servlet:
    context-path: /identity
#Define JDBC Connection
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 123456
  main:
    banner-mode: off
#config JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#define Signed_key:
jwt:
  signerKey: "SMAa5eczOGLtGEkN6+idEo+HtC+/AxUuoB4aEf91DON30ma+B0raKnzkPjsf2KvF"
